services:

  stats-db:
    image: postgres:16.1
    container_name: explore-postgres-stats
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=explore-stats
      - POSTGRES_USER=explore-stats
      - POSTGRES_DB=explore-stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  main-db:
    image: postgres:16.1
    container_name: explore-postgres-main
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=explore-main
      - POSTGRES_USER=explore-main
      - POSTGRES_DB=explore-main
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10