server:
  port: 0

stats-server:
  url: "http://stats-server"

spring:

  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
    database: POSTGRESQL
    show-sql: false

  sql:
    init:
      mode: always

  jackson:
    serialization:
      fail-on-empty-beans: false

  main:
    banner-mode: off
    log-startup-info: false

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewm_category
    username: postgres
    password: postgres

logging:
  level:
    org:
      zalando.logbook: TRACE
      springframework:
        orm:
          jpa: INFO
        transaction: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

grpc:
  client:
    analyzer:
      address: 'discovery:///analyzer'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    collector:
      address: 'discovery:///collector'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext