CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id BIGINT                                    NOT NULL,
    event_id     BIGINT                                    NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    status       VARCHAR(16)                               NOT NULL
);