CREATE TABLE IF NOT EXISTS event_locations (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	annotation         VARCHAR(2000),
    category           BIGINT NOT NULL,
	created_on         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	description        text,
	event_date         TIMESTAMP WITHOUT TIME ZONE,
    initiator          BIGINT NOT NULL,
    location_id        BIGINT REFERENCES event_locations (id) ON DELETE CASCADE,
    paid               BOOLEAN,
    participant_limit  INTEGER,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN NOT NULL,
    state              VARCHAR(16),
    title              VARCHAR(120)
);

CREATE TABLE IF NOT EXISTS compilations (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN NOT NULL,
    title  VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS events_compilations (
    event          BIGINT NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    compilation    BIGINT NOT NULL REFERENCES compilations (id) ON DELETE CASCADE
)