grpc.server.port: 0
spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
  sql:
    init:
      mode: always
  main:
    banner-mode: off
    log-startup-info: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewm_stats_db
    #driverClassName: org.h2.Driver
    #url: jdbc:h2:file:./db/stats
    username: postgres
    password: postgres

kafka.constants:
  url: "localhost:9092"
  action: "stats.user-actions.v1"
  similarity: "stats.events-similarity.v1"