server:
  port: 0
  uri: http://stats-server:{server.port}
spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
  sql:
    init:
      mode: always
  main:
    banner-mode: off
    log-startup-info: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6432/explore-stats
    #driverClassName: org.h2.Driver
    #url: jdbc:h2:file:./db/stats
    username: ${explore_stats_username}
    password: ${explore_stats_username}