server:
  port: 0

stats-server:
  url: "http://stats-server"

spring:

  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
    database: POSTGRESQL
    show-sql: true

  sql:
    init:
      mode: always

  jackson:
    serialization:
      fail-on-empty-beans: false

  main:
    banner-mode: off
    log-startup-info: false

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/explore-main
    username: explore-main
    password: explore-main

logging:
  level:
    org:
      zalando.logbook: TRACE
      springframework:
        orm:
          jpa: INFO
        transaction: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
